### ISSUE TITLE
CVEs 0 of 0, No CVE's available

### ISSUE THREAD

**Issue by mon369** [Secure-Compliance-Solutions-LLC/GVM-Docker#6]
The feed shows that the CVE is up to date, and was been synced, but when I look at X.X.X.X:8080/cves, it shows nothing.  What could the issue be?

Is scap data an important piece of GVM?  Or can GVM function without it?

**Comment by pixelsquared** [comment]
This relates to issue #3 
The missing data is not required for scans to complete but is used when viewing the scan results.

**Comment by pixelsquared** [comment]
This Issue should be fixed with the latest commit

**Comment by david-colombo** [comment]
Hey,
I pulled and started the latest securecompliance/gvm docker from dockerhub today.
(Which should include the patch for this bug already.)

But even after an hour runtime the CVE and CPE data are still not available.

Any news on this bug?

**Comment by pixelsquared** [comment]
Could you try leaving the container running for a few hours and see if that works?

**Comment by david-colombo** [comment]
Okay, will post an update later/tomorrow whether the data showed up then or not.

Thanks for your help.

**Comment by david-colombo** [comment]
Hey, 16 hours later, the data showed up \o/

Just out of curiosity, do you know why it takes so long?

PS: The CERT data don’t have a severity (due the limitations of community feed or is this another bug/issue?)

**Comment by pixelsquared** [comment]
I have created a new issue for the load speed for the data. #13
Not sure why the CERT data don’t have a severity will look in to it.
